import { AnalysisWithUser } from './analyses.service';

export function buildAnalysisSnapshot(analysis: AnalysisWithUser) {
  return {
    id: analysis.id,
    userId: analysis.userId,
    projectType: analysis.projectType,
    city: analysis.city,
    district: analysis.district,
    budget: analysis.budget ? Number(analysis.budget) : null,
    budgetRange: analysis.budgetRange,
    propertyType: analysis.propertyType,
    surface: analysis.surface,
    surfaceRange: analysis.surfaceRange,
    urgency: analysis.urgency,
    objective: analysis.objective,
    message: analysis.message,
    profession: analysis.profession,
    maritalStatus: analysis.maritalStatus,
    hasChildren: analysis.hasChildren,
    childrenCount: analysis.childrenCount,
    personalNotes: analysis.personalNotes,
    consentAccepted: analysis.consentAccepted,
    score: analysis.score,
    maturityLevel: analysis.maturityLevel,
    commercialPriority: analysis.commercialPriority,
    profileType: analysis.profileType,
    recommendedService: analysis.recommendedService,
    strengths: analysis.strengths,
    missingInfo: analysis.missingInfo,
    recommendations: analysis.recommendations,
    nextAction: analysis.nextAction,
    status: analysis.status,
    createdAt: analysis.createdAt,
    updatedAt: analysis.updatedAt,
    user: {
      id: analysis.user.id,
      firstName: analysis.user.firstName,
      lastName: analysis.user.lastName,
      email: analysis.user.email,
      phone: analysis.user.phone,
    },
  };
}
